version: '3.1'
services:
  api:
    build: api
    command: yarn dev
    environment:
      NODE_ENV: development
    volumes:
      - ./api/:/app
      - /app/node_modules

  frontend:
    build: frontend
    environment:
      NODE_ENV: development
    volumes:
      - ./frontend/:/app
      - /app/node_modules
