version: '3.1'
services:
  api:
    image: api:latest
    command: node bin/www
    environment:
      NODE_ENV: production

  frontend:
    image: frontend:latest
    command: yarn run pushstate-server -p 3000 -d dist