version: '3.1'
services:
  mongo:
    image: mongo:latest
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example

  api:
    container_name: api
    restart: always
    ports:
      - 3001:3001
    environment:
      MONGO_URI: mongodb://root:example@mongo/desafio_dev?authSource=admin
      PORT: 3001
    links:
      - mongo

  frontend:
    container_name: frontend
    restart: always
    ports:
      - 3000:3000
    environment:
      API_URI: api